language: ruby
script: 
  - "rake lint"
  - "rake spec"
  - "rake validate"
branches:
  only:
    - master
    - puppet-v4.0
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 54.0"  
  - rvm: 2.4.4
    env: PUPPET_GEM_VERSION="~> 5.0"
  - rvm: 2.5.1
    env: PUPPET_GEM_VERSION="~> 5.0"
notifications:
  email: false
gemfile: .gemfile
